# Number of days of inactivity before an issue becomes stale
daysUntilStale: 90
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 1
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - no-stale

# Label to use when marking an issue as stale
staleLabel: wontfix

markComment: false

# Comment to post when marking an issue as stale. Set to `false` to disable
closeComment: >
  This issue has been automatically closed as stale.
  This mechanism helps to prioritize feature requests which received more support from the community.
  If you want to open again this issue you have to provide a Pull Request.
